import OAI.Computability.FourierCircuit.TripleSpan
import Mathlib.Data.Finset.Card
import Mathlib.Tactic

/-!
# Span obstruction for grouped incidence moments

A grouped incidence moment `sum_{i in C} a_i` touches every source triple
intersecting `C`.  When `C` has at least two coordinates, those triple
indicators already span the full active address factor.  Consequently a
simple grouping of two or more singleton moments cannot retain the
codimension-one source label enjoyed by an individual `a_i`.

This is a label-span fact only; it does not lower-bound arbitrary weighted
factorizations or framed networks.
-/

namespace OAI
namespace ExactFourier
namespace GroupedMomentSpan

open FrameLabels TripleSpan

 def groupedTripleIndicators {h : ℕ} (C : Finset (Fin h)) : Set (Fin h → ZMod 2) :=
  {v | ∃ T : Finset (Fin h), T.card = 3 ∧ (T ∩ C).Nonempty ∧ v = indicator T}

abbrev GroupedSpan {h : ℕ} (C : Finset (Fin h)) :
    Submodule (ZMod 2) (Fin h → ZMod 2) :=
  Submodule.span (ZMod 2) (groupedTripleIndicators C)

theorem grouped_indicator_mem_span {h : ℕ} (C T : Finset (Fin h))
    (hT : T.card = 3) (hTC : (T ∩ C).Nonempty) :
    indicator T ∈ GroupedSpan C := by
  apply Submodule.subset_span
  exact ⟨T, hT, hTC, rfl⟩

/-- Every basis vector is generated by triples meeting `C`, assuming at least
 two points of `C` and four points in the active factor. -/
theorem basisVec_mem_groupedSpan {h : ℕ} (hh : 4 ≤ h)
    (C : Finset (Fin h)) (hC : 2 ≤ C.card) (i : Fin h) :
    basisVec i ∈ GroupedSpan C := by
  classical
  by_cases hiC : i ∈ C
  · obtain ⟨a, b, c, hai, hbi, hba, hci, hca, hcb⟩ :=
      exists_three_away (by omega : 3 < h) i
    have hab : ({i, a, b} : Finset (Fin h)).card = 3 := by
      simp [hai, hai.symm, hbi, hbi.symm, hba, hba.symm]
    have hac : ({i, a, c} : Finset (Fin h)).card = 3 := by
      simp [hai, hai.symm, hci, hci.symm, hca, hca.symm]
    have hbc : ({i, b, c} : Finset (Fin h)).card = 3 := by
      simp [hbi, hbi.symm, hci, hci.symm, hcb, hcb.symm]
    have hiab : (({i, a, b} : Finset (Fin h)) ∩ C).Nonempty := by
      exact ⟨i, by simp [hiC]⟩
    have hiac : (({i, a, c} : Finset (Fin h)) ∩ C).Nonempty := by
      exact ⟨i, by simp [hiC]⟩
    have hibc : (({i, b, c} : Finset (Fin h)) ∩ C).Nonempty := by
      exact ⟨i, by simp [hiC]⟩
    have hab' := grouped_indicator_mem_span C ({i, a, b} : Finset (Fin h)) hab hiab
    have hac' := grouped_indicator_mem_span C ({i, a, c} : Finset (Fin h)) hac hiac
    have hbc' := grouped_indicator_mem_span C ({i, b, c} : Finset (Fin h)) hbc hibc
    rw [four_point_indicator_identity i a b c hai hbi hba hci hca hcb]
    exact (GroupedSpan C).add_mem ((GroupedSpan C).add_mem hab' hac') hbc'
  · obtain ⟨a, haC, b, hbC, hab⟩ :=
      Finset.one_lt_card.mp (by omega : 1 < C.card)
    have hai : a ≠ i := by
      intro hai
      exact hiC (hai ▸ haC)
    have hbi : b ≠ i := by
      intro hbi
      exact hiC (hbi ▸ hbC)
    -- The helper may choose names different from `a,b`; choose a fresh point
    -- directly from the finite complement of `{i,a,b}`.
    let forbidden : Finset (Fin h) := {i, a, b}
    have hforbidden : forbidden.card = 3 := by
      simp [forbidden, hai, hai.symm, hbi, hbi.symm, hab, hab.symm]
    have hlt : forbidden.card < (Finset.univ : Finset (Fin h)).card := by
      rw [hforbidden, Finset.card_univ, Fintype.card_fin]
      omega
    obtain ⟨c, hcuniv, hcforbidden⟩ :=
      Finset.exists_mem_notMem_of_card_lt_card hlt
    have hci : c ≠ i := by
      intro e
      exact hcforbidden (by simp [forbidden, e])
    have hca : c ≠ a := by
      intro e
      exact hcforbidden (by simp [forbidden, e])
    have hcb : c ≠ b := by
      intro e
      exact hcforbidden (by simp [forbidden, e])
    have hab3 : ({i, a, b} : Finset (Fin h)).card = 3 := by
      simp [hai, hai.symm, hbi, hbi.symm, hab, hab.symm]
    have hac3 : ({i, a, c} : Finset (Fin h)).card = 3 := by
      simp [hai, hai.symm, hci, hci.symm, hca, hca.symm]
    have hbc3 : ({i, b, c} : Finset (Fin h)).card = 3 := by
      simp [hbi, hbi.symm, hci, hci.symm, hcb, hcb.symm]
    have hiab : (({i, a, b} : Finset (Fin h)) ∩ C).Nonempty := by
      exact ⟨a, by simp [haC]⟩
    have hiac : (({i, a, c} : Finset (Fin h)) ∩ C).Nonempty := by
      exact ⟨a, by simp [haC]⟩
    have hibc : (({i, b, c} : Finset (Fin h)) ∩ C).Nonempty := by
      exact ⟨b, by simp [hbC]⟩
    have hab' := grouped_indicator_mem_span C ({i, a, b} : Finset (Fin h)) hab3 hiab
    have hac' := grouped_indicator_mem_span C ({i, a, c} : Finset (Fin h)) hac3 hiac
    have hbc' := grouped_indicator_mem_span C ({i, b, c} : Finset (Fin h)) hbc3 hibc
    rw [four_point_indicator_identity i a b c hai hbi hab.symm hci hca hcb]
    exact (GroupedSpan C).add_mem ((GroupedSpan C).add_mem hab' hac') hbc'

 theorem groupedSpan_eq_top {h : ℕ} (hh : 4 ≤ h)
    (C : Finset (Fin h)) (hC : 2 ≤ C.card) :
    GroupedSpan C = ⊤ := by
  apply (Submodule.eq_top_iff_forall_basis_mem
    (Pi.basisFun (ZMod 2) (Fin h))).2
  intro i
  rw [Pi.basisFun_apply]
  exact basisVec_mem_groupedSpan hh C hC i

 theorem h24_groupedSpan_eq_top (C : Finset (Fin 24))
    (hC : 2 ≤ C.card) : GroupedSpan C = ⊤ := by
  exact groupedSpan_eq_top (by norm_num) C hC

end GroupedMomentSpan
end ExactFourier
end OAI
