import OAI.Computability.FourierCircuit.ConcreteQuadraticPhase

/-!
# A two-coordinate nested projected phase toy

`coordinateLine w` and `coordinatePlane w z` are the first nontrivial nested
orthogonal projections.  This file is deliberately a local toy: it gives
exact kernels and a rank-one residual, but makes no all-length schedule claim.
-/

namespace OAI
namespace ExactFourier
namespace NestedCoordinateProjection

open AddressPhaseConjugation
open BinaryTransvection
open ConcreteQuadraticPhase

abbrev F2 := BinaryAddressPermutation.F2
abbrev Address (ι : Type) := BinaryAddressPermutation.Address ι

variable {ι : Type} [Fintype ι] [DecidableEq ι]

/-- The two-coordinate plane generated by `e_w,e_z`. -/
def coordinatePlane (w z : ι) : Submodule F2 (Address ι) :=
  Submodule.span F2 ({coordinate w, coordinate z} : Set (Address ι))

/-- The coordinate projection onto the two-coordinate plane. -/
noncomputable def coordinateProjectionTwo (w z : ι) :
    Address ι →ₗ[F2] Address ι :=
  coordinateProjection w + coordinateProjection z

theorem coordinateProjectionTwo_apply (w z : ι) (x : Address ι) :
    coordinateProjectionTwo w z x =
      x w • coordinate w + x z • coordinate z := by
  change coordinateProjection w x + coordinateProjection z x = _
  rw [coordinateProjection_apply, coordinateProjection_apply]

theorem coordinateLine_le_coordinatePlane (w z : ι) :
    coordinateLine w ≤ coordinatePlane w z := by
  intro x hx
  rcases Submodule.mem_span_singleton.mp hx with ⟨a, rfl⟩
  exact Submodule.smul_mem _ _ (Submodule.subset_span (by simp))

theorem coordinateLine_z_le_coordinatePlane (w z : ι) :
    coordinateLine z ≤ coordinatePlane w z := by
  intro x hx
  rcases Submodule.mem_span_singleton.mp hx with ⟨a, rfl⟩
  exact Submodule.smul_mem _ _ (Submodule.subset_span (by simp))

theorem coordinateLine_z_le_orthogonal_line_w (w z : ι) (hzw : z ≠ w) :
    coordinateLine z ≤ (coordinateLine w).orthogonalBilin
      (BinaryTransvection.bilinearDot : _) := by
  rw [coordinateLine_orthogonal]
  intro x hx
  rcases Submodule.mem_span_singleton.mp hx with ⟨a, rfl⟩
  rw [LinearMap.mem_ker]
  simp [coordinateEval, coordinate, hzw, Ne.symm hzw]

theorem coordinateLine_disjoint_line_z (w z : ι) (hzw : z ≠ w) :
    Disjoint (coordinateLine w) (coordinateLine z) := by
  rw [Submodule.disjoint_def]
  intro u huw huz
  rcases Submodule.mem_span_singleton.mp huw with ⟨a, ha⟩
  rcases Submodule.mem_span_singleton.mp huz with ⟨b, hb⟩
  have haw : a = 0 := by
    have ha_w := congrFun ha w
    have hb_w := congrFun hb w
    have ha_eq : a = u w := by
      simpa [coordinate] using ha_w
    have hzero : (0 : F2) = u w := by
      simpa [coordinate, hzw, Ne.symm hzw] using hb_w
    exact ha_eq.trans hzero.symm
  calc
    u = a • coordinate w := ha.symm
    _ = 0 := by rw [haw, zero_smul]

theorem coordinatePlane_eq_sup_lines (w z : ι) :
    coordinatePlane w z = coordinateLine w ⊔ coordinateLine z := by
  apply le_antisymm
  · unfold coordinatePlane
    rw [Submodule.span_le]
    intro y hy
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hy
    rcases hy with rfl | rfl
    · exact Submodule.mem_sup_left (Submodule.subset_span (by simp))
    · exact Submodule.mem_sup_right (Submodule.subset_span (by simp))
  · exact sup_le (coordinateLine_le_coordinatePlane w z)
      (coordinateLine_z_le_coordinatePlane w z)

theorem coordinatePlane_nested_residual_certificate
    (w z : ι) (hzw : z ≠ w) :
    coordinateLine w ≤ coordinatePlane w z ∧
      coordinatePlane w z = coordinateLine w ⊔ coordinateLine z ∧
      Disjoint (coordinateLine w) (coordinateLine z) ∧
      coordinateLine z ≤ (coordinateLine w).orthogonalBilin
        (BinaryTransvection.bilinearDot : _) ∧
      Module.finrank F2 (coordinateLine z) = 1 := by
  have hne : coordinate z ≠ (0 : Address ι) := by
    intro h
    have hz := congrFun h z
    simpa [coordinate] using hz
  exact ⟨coordinateLine_le_coordinatePlane w z,
    coordinatePlane_eq_sup_lines w z,
    coordinateLine_disjoint_line_z w z hzw,
    coordinateLine_z_le_orthogonal_line_w w z hzw,
    finrank_span_singleton hne⟩

theorem coordinateProjectionTwo_mem_plane (w z : ι) (x : Address ι) :
    coordinateProjectionTwo w z x ∈ coordinatePlane w z := by
  rw [coordinateProjectionTwo_apply]
  exact (coordinatePlane w z).add_mem
    (Submodule.smul_mem _ _ (Submodule.subset_span (by simp)))
    (Submodule.smul_mem _ _ (Submodule.subset_span (by simp)))

theorem coordinateProjectionTwo_fixed_plane (w z : ι) (hzw : z ≠ w)
    {u : Address ι} (hu : u ∈ coordinatePlane w z) :
    coordinateProjectionTwo w z u = u := by
  unfold coordinatePlane at hu
  refine Submodule.span_induction
    (p := fun y _ => coordinateProjectionTwo w z y = y) ?_ ?_ ?_ ?_ hu
  · intro y hy
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hy
    rcases hy with rfl | rfl
    · simp [coordinateProjectionTwo_apply, coordinateEval, coordinate, hzw,
        Ne.symm hzw]
    · simp [coordinateProjectionTwo_apply, coordinateEval, coordinate, hzw,
        Ne.symm hzw]
  · simp [coordinateProjectionTwo_apply]
  · intro x y _ _ hx hy
    rw [map_add, hx, hy]
  · intro a x _ hx
    rw [map_smul, hx]

theorem coordinateProjectionTwo_idem (w z : ι) (hzw : z ≠ w) (x : Address ι) :
    coordinateProjectionTwo w z (coordinateProjectionTwo w z x) =
      coordinateProjectionTwo w z x :=
  coordinateProjectionTwo_fixed_plane w z hzw (coordinateProjectionTwo_mem_plane w z x)

theorem coordinateProjectionTwo_kernel (w z : ι) (hzw : z ≠ w) :
    LinearMap.ker (coordinateProjectionTwo w z) =
      (coordinatePlane w z).orthogonalBilin
        (BinaryTransvection.bilinearDot : _) := by
  ext x
  constructor
  · intro hx
    rw [LinearMap.mem_ker] at hx
    have hw : x w = 0 := by
      have h := congrFun hx w
      simpa [coordinateProjectionTwo_apply, coordinate, hzw] using h
    have hz : x z = 0 := by
      have h := congrFun hx z
      simpa [coordinateProjectionTwo_apply, coordinate, hzw] using h
    unfold coordinatePlane
    rw [Submodule.mem_orthogonalBilin_span]
    intro a ha
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at ha
    rcases ha with rfl | rfl
    · change dotProduct (coordinate w) x = 0
      rw [coordinate_dot]
      exact hw
    · change dotProduct (coordinate z) x = 0
      rw [coordinate_dot]
      exact hz
  · intro hx
    unfold coordinatePlane at hx
    rw [Submodule.mem_orthogonalBilin_span] at hx
    have hw : x w = 0 := by
      have h := @hx (coordinate w) (by simp)
      change dotProduct (coordinate w) x = 0 at h
      simpa [coordinate_dot] using h
    have hz : x z = 0 := by
      have h := @hx (coordinate z) (by simp)
      change dotProduct (coordinate z) x = 0 at h
      simpa [coordinate_dot] using h
    rw [LinearMap.mem_ker, coordinateProjectionTwo_apply]
    rw [hw, hz]
    simp

theorem coordinateProjection_comp_two (w z : ι) (hzw : z ≠ w) :
    coordinateProjection w ∘ₗ coordinateProjectionTwo w z =
      coordinateProjection w := by
  apply LinearMap.ext
  intro x
  simp [LinearMap.comp_apply, coordinateProjection_apply,
    coordinateProjectionTwo_apply, coordinateEval, coordinate, hzw,
    Ne.symm hzw]

theorem coordinateProjectionTwo_comp (w z : ι) (hzw : z ≠ w) :
    coordinateProjectionTwo w z ∘ₗ coordinateProjection w =
      coordinateProjection w := by
  apply LinearMap.ext
  intro x
  rw [LinearMap.comp_apply]
  exact coordinateProjectionTwo_fixed_plane w z hzw
    ((coordinateLine_le_coordinatePlane w z)
      (coordinateProjection_mem_line w x))

/-- In characteristic two the nested residual is the second coordinate
projection.  Thus its image is exactly one coordinate line. -/
noncomputable def coordinateResidual (w z : ι) : Address ι →ₗ[F2] Address ι :=
  coordinateProjectionTwo w z + coordinateProjection w

theorem coordinateResidual_eq_projection_z (w z : ι) :
    coordinateResidual w z = coordinateProjection z := by
  apply LinearMap.ext
  intro x
  change coordinateProjectionTwo w z x + coordinateProjection w x =
    coordinateProjection z x
  rw [coordinateProjectionTwo_apply]
  simp only [coordinateProjection_apply]
  calc
    x w • coordinate w + x z • coordinate z + x w • coordinate w =
        x w • coordinate w + x w • coordinate w + x z • coordinate z := by
          ac_rfl
    _ = x z • coordinate z := by
      have hzero : x w • coordinate w + x w • coordinate w = 0 := by
        ext i
        simp only [Pi.add_apply, Pi.smul_apply, smul_eq_mul]
        rw [← add_mul, CharTwo.add_self_eq_zero, zero_mul]
        simp
      rw [hzero, zero_add]

theorem coordinateResidual_range (w z : ι) (hzw : z ≠ w) :
    LinearMap.range (coordinateResidual w z) = coordinateLine z := by
  rw [coordinateResidual_eq_projection_z]
  apply le_antisymm
  · rintro y ⟨x, rfl⟩
    exact coordinateProjection_mem_line z x
  · intro y hy
    rcases Submodule.mem_span_singleton.mp hy with ⟨a, rfl⟩
    refine ⟨a • coordinate z, ?_⟩
    rw [coordinateProjection_fixed_line]
    exact Submodule.smul_mem _ _ (Submodule.mem_span_singleton_self _)

end NestedCoordinateProjection
end ExactFourier
end OAI

namespace OAI
namespace ExactFourier
namespace NestedCoordinateProjection

open BinaryTransvection
open ConcreteQuadraticPhase

variable {ι : Type} [Fintype ι] [DecidableEq ι]

lemma coordinate_ne_zero (z : ι) : coordinate z ≠ (0 : Address ι) := by
  intro h
  have hz := congrFun h z
  simpa [coordinate] using hz

theorem coordinateResidual_finrank (w z : ι) (hzw : z ≠ w) :
    Module.finrank F2 (LinearMap.range (coordinateResidual w z)) = 1 := by
  rw [coordinateResidual_range w z hzw]
  exact finrank_span_singleton (coordinate_ne_zero z)

end NestedCoordinateProjection
end ExactFourier
end OAI
